stations = [{'dialog_flow_entity': 'twelfth street oakland city center',
             'written_name': '12th St. Oakland City Center',
             'abbr': '12TH',
             'spoken_name': 'twelfth street oakland city center',
             'synonyms': ['twelfth street',
                          'oakland city center',
                          'twelfth street oakland',
                          'oakland twelfth street']},
            {'dialog_flow_entity': 'sixteenth street mission',
             'written_name': '16th St. Mission',
             'abbr': '16TH',
             'spoken_name': 'sixteenth street mission',
             'synonyms': ['sixteenth street mission, sixteenth street',
                          'sixteenth mission',
                          'sixteen mission']},
            {'dialog_flow_entity': 'nineteenth street oakland',
             'written_name': '19th St. Oakland',
             'abbr': '19TH',
             'spoken_name': 'nineteeth street oakland',
             'synonyms': ['nineteenth oakland']},
            {'dialog_flow_entity': '24th street mission',
             'written_name': '24th St. Mission',
             'abbr': '24TH',
             'spoken_name': '24th street mission',
             'synonyms': ['twenty fourth street mission']},
            {'dialog_flow_entity': 'ashby',
             'written_name': 'Ashby',
             'abbr': 'ASHB',
             'spoken_name': 'ashby',
             'synonyms': []},
            {'dialog_flow_entity': 'balboa park',
             'written_name': 'Balboa Park',
             'abbr': 'BALB',
             'spoken_name': 'balboa park',
             'synonyms': []},
            {'dialog_flow_entity': 'bay fair',
             'written_name': 'Bay Fair',
             'abbr': 'BAYF',
             'spoken_name': 'bay fair',
             'synonyms': ['Bayfair']},
            {'dialog_flow_entity': 'castro valley',
             'written_name': 'Castro Valley',
             'abbr': 'CAST',
             'spoken_name': 'castro valley',
             'synonyms': ['Castro']},
            {'dialog_flow_entity': 'civic center u n plaza',
             'written_name': 'Civic Center/UN Plaza',
             'abbr': 'CIVC',
             'spoken_name': 'civic center u n plaza',
             'synonyms': ['Civic Center', 'UN Plaza']},
            {'dialog_flow_entity': 'coliseum',
             'written_name': 'Coliseum',
             'abbr': 'COLS',
             'spoken_name': 'coliseum',
             'synonyms': []},
            {'dialog_flow_entity': 'colma',
             'written_name': 'Colma',
             'abbr': 'COLM',
             'spoken_name': 'colma',
             'synonyms': []},
            {'dialog_flow_entity': 'concord',
             'written_name': 'Concord',
             'abbr': 'CONC',
             'spoken_name': 'concord',
             'synonyms': []},
            {'dialog_flow_entity': 'daly city',
             'written_name': 'Daly City',
             'abbr': 'DALY',
             'spoken_name': 'daly city',
             'synonyms': []},
            {'dialog_flow_entity': 'downtown berkeley',
             'written_name': 'Downtown Berkeley',
             'abbr': 'DBRK',
             'spoken_name': 'downtown berkeley',
             'synonyms': ['Berkeley']},
            {'dialog_flow_entity': 'dublin pleasanton',
             'written_name': 'Dublin/Pleasanton',
             'abbr': 'DUBL',
             'spoken_name': 'dublin pleasanton',
             'synonyms': ['Dublin', 'Pleasanton']},
            {'dialog_flow_entity': 'el cerrito del norte',
             'written_name': 'El Cerrito del Norte',
             'abbr': 'DELN',
             'spoken_name': 'el cerrito del norte',
             'synonyms': ['El cerrito norte', 'el cerrito north', 'cerrito norte']},
            {'dialog_flow_entity': 'el cerrito plaza',
             'written_name': 'El Cerrito Plaza',
             'abbr': 'PLZA',
             'spoken_name': 'el cerrito plaza',
             'synonyms': ['cerrito plaza']},
            {'dialog_flow_entity': 'embarcadero',
             'written_name': 'Embarcadero',
             'abbr': 'EMBR',
             'spoken_name': 'embarcadero',
             'synonyms': []},
            {'dialog_flow_entity': 'fremont',
             'written_name': 'Fremont',
             'abbr': 'FRMT',
             'spoken_name': 'fremont',
             'synonyms': []},
            {'dialog_flow_entity': 'fruitvale',
             'written_name': 'Fruitvale',
             'abbr': 'FTVL',
             'spoken_name': 'fruitvale',
             'synonyms': []},
            {'dialog_flow_entity': 'glen park',
             'written_name': 'Glen Park',
             'abbr': 'GLEN',
             'spoken_name': 'glen park',
             'synonyms': []},
            {'dialog_flow_entity': 'hayward',
             'written_name': 'Hayward',
             'abbr': 'HAYW',
             'spoken_name': 'hayward',
             'synonyms': []},
            {'dialog_flow_entity': 'lafayette',
             'written_name': 'Lafayette',
             'abbr': 'LAFY',
             'spoken_name': 'lafayette',
             'synonyms': []},
            {'dialog_flow_entity': 'lake merritt',
             'written_name': 'Lake Merritt',
             'abbr': 'LAKE',
             'spoken_name': 'lake merritt',
             'synonyms': []},
            {'dialog_flow_entity': 'macarthur',
             'written_name': 'MacArthur',
             'abbr': 'MCAR',
             'spoken_name': 'macarthur',
             'synonyms': []},
            {'dialog_flow_entity': 'millbrae',
             'written_name': 'Millbrae',
             'abbr': 'MLBR',
             'spoken_name': 'millbrae',
             'synonyms': []},
            {'dialog_flow_entity': 'montgomery',
             'written_name': 'Montgomery St.',
             'abbr': 'MONT',
             'spoken_name': 'montgomery',
             'synonyms': ['Montgomery Street', 'Montgomory']},
            {'dialog_flow_entity': 'north berkeley',
             'written_name': 'North Berkeley',
             'abbr': 'NBRK',
             'spoken_name': 'north berkeley',
             'synonyms': []},
            {'dialog_flow_entity': 'north concord/martinez',
             'written_name': 'North Concord/Martinez',
             'abbr': 'NCON',
             'spoken_name': 'north concord/martinez',
             'synonyms': ['North Concord', 'Martinez']},
            {'dialog_flow_entity': "oakland international airport",
             'written_name': "Oakland Int'l Airport",
             'abbr': 'OAKL',
             'spoken_name': "oakland international airport",
             'synonyms': ['O.A.K', 'Oakland Airport', 'Oakland International Airport']},
            {'dialog_flow_entity': 'orinda',
             'written_name': 'Orinda',
             'abbr': 'ORIN',
             'spoken_name': 'orinda',
             'synonyms': []},
            {'dialog_flow_entity': 'pittsburg bay point',
             'written_name': 'Pittsburg/Bay Point',
             'abbr': 'PITT',
             'spoken_name': 'pittsburg bay point',
             'synonyms': ['Pittsburg', 'Pittsburg Bay Point', 'Bay Point']},
            {'dialog_flow_entity': 'pleasant hill/contra costa centre',
             'written_name': 'Pleasant Hill Contra Costa Centre',
             'abbr': 'PHIL',
             'spoken_name': 'pleasant hill contra costa centre',
             'synonyms': ['Pleasant Hill', 'Contra Costa Centre']},
            {'dialog_flow_entity': 'powell street',
             'written_name': 'Powell St.',
             'abbr': 'POWL',
             'spoken_name': 'powell street',
             'synonyms': ['Powell']},
            {'dialog_flow_entity': 'richmond',
             'written_name': 'Richmond',
             'abbr': 'RICH',
             'spoken_name': 'richmond',
             'synonyms': []},
            {'dialog_flow_entity': 'rockridge',
             'written_name': 'Rockridge',
             'abbr': 'ROCK',
             'spoken_name': 'rockridge',
             'synonyms': []},
            {'dialog_flow_entity': 'san bruno',
             'written_name': 'San Bruno',
             'abbr': 'SBRN',
             'spoken_name': 'san bruno',
             'synonyms': []},
            {'dialog_flow_entity': "san francisco international airport",
             'written_name': "San Francisco Int'l Airport",
             'abbr': 'SFIA',
             'spoken_name': "san francisco international airport",
             'synonyms': ['SFO', 'S.F.O.']},
            {'dialog_flow_entity': 'san leandro',
             'written_name': 'San Leandro',
             'abbr': 'SANL',
             'spoken_name': 'san leandro',
             'synonyms': []},
            {'dialog_flow_entity': 'south hayward',
             'written_name': 'South Hayward',
             'abbr': 'SHAY',
             'spoken_name': 'south hayward',
             'synonyms': []},
            {'dialog_flow_entity': 'south san francisco',
             'written_name': 'South San Francisco',
             'abbr': 'SSAN',
             'spoken_name': 'south san francisco',
             'synonyms': []},
            {'dialog_flow_entity': 'union city',
             'written_name': 'Union City',
             'abbr': 'UCTY',
             'spoken_name': 'union city',
             'synonyms': []},
            {'dialog_flow_entity': 'walnut creek',
             'written_name': 'Walnut Creek',
             'abbr': 'WCRK',
             'spoken_name': 'walnut creek',
             'synonyms': []},
            {'dialog_flow_entity': 'west dublin pleasanton',
             'written_name': 'West Dublin/Pleasanton',
             'abbr': 'WDUB',
             'spoken_name': 'west dublin pleasanton',
             'synonyms': ['West Dublin']},
            {'dialog_flow_entity': 'west oakland',
             'written_name': 'West Oakland',
             'abbr': 'WOAK',
             'spoken_name': 'west oakland',
             'synonyms': []}]
